/*
* Copyright 2023 nanato12
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AttachModuleResponse : Attach by operation of the module channel provider



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachModuleResponse {
    /// User ID of the bot on the LINE Official Account.
    #[serde(rename = "bot_id")]
    pub bot_id: String,
    /// Permissions (scope) granted by the LINE Official Account admin.
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
}

impl AttachModuleResponse {
    /// Attach by operation of the module channel provider
    pub fn new(bot_id: String, scopes: Vec<String>) -> AttachModuleResponse {
        AttachModuleResponse {
            bot_id,
            scopes,
        }
    }
}


