/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudienceGroupType : Audience group type
/// Audience group type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum AudienceGroupType {
#[serde(rename = "UPLOAD")]
    Upload,
#[serde(rename = "CLICK")]
    Click,
#[serde(rename = "IMP")]
    Imp,
#[serde(rename = "CHAT_TAG")]
    ChatTag,
#[serde(rename = "FRIEND_PATH")]
    FriendPath,
#[serde(rename = "RESERVATION")]
    Reservation,
#[serde(rename = "APP_EVENT")]
    AppEvent,
#[serde(rename = "VIDEO_VIEW")]
    VideoView,
#[serde(rename = "WEBTRAFFIC")]
    Webtraffic,
#[serde(rename = "IMAGE_CLICK")]
    ImageClick,
#[serde(rename = "RICHMENU_IMP")]
    RichmenuImp,
#[serde(rename = "RICHMENU_CLICK")]
    RichmenuClick,
#[serde(rename = "POP_AD_IMP")]
    PopAdImp,
#[serde(rename = "TRACKINGTAG_WEBTRAFFIC")]
    TrackingtagWebtraffic,
}

impl std::fmt::Display for AudienceGroupType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
Self::Upload => write!(f, "UPLOAD"),
Self::Click => write!(f, "CLICK"),
Self::Imp => write!(f, "IMP"),
Self::ChatTag => write!(f, "CHAT_TAG"),
Self::FriendPath => write!(f, "FRIEND_PATH"),
Self::Reservation => write!(f, "RESERVATION"),
Self::AppEvent => write!(f, "APP_EVENT"),
Self::VideoView => write!(f, "VIDEO_VIEW"),
Self::Webtraffic => write!(f, "WEBTRAFFIC"),
Self::ImageClick => write!(f, "IMAGE_CLICK"),
Self::RichmenuImp => write!(f, "RICHMENU_IMP"),
Self::RichmenuClick => write!(f, "RICHMENU_CLICK"),
Self::PopAdImp => write!(f, "POP_AD_IMP"),
Self::TrackingtagWebtraffic => write!(f, "TRACKINGTAG_WEBTRAFFIC"),
}
    }
}

impl Default for AudienceGroupType {
    fn default() -> AudienceGroupType {
        Self::Upload
    }
}
