/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum AreaDemographic {
    #[serde(rename = "jp_01")]
    HOKKAIDO,
    #[serde(rename = "jp_02")]
    AOMORI,
    #[serde(rename = "jp_03")]
    IWATE,
    #[serde(rename = "jp_04")]
    MIYAGI,
    #[serde(rename = "jp_05")]
    AKITA,
    #[serde(rename = "jp_06")]
    YAMAGATA,
    #[serde(rename = "jp_07")]
    FUKUSHIMA,
    #[serde(rename = "jp_08")]
    IBARAKI,
    #[serde(rename = "jp_09")]
    TOCHIGI,
    #[serde(rename = "jp_10")]
    GUNMA,
    #[serde(rename = "jp_11")]
    SAITAMA,
    #[serde(rename = "jp_12")]
    CHIBA,
    #[serde(rename = "jp_13")]
    TOKYO,
    #[serde(rename = "jp_14")]
    KANAGAWA,
    #[serde(rename = "jp_15")]
    NIIGATA,
    #[serde(rename = "jp_16")]
    TOYAMA,
    #[serde(rename = "jp_17")]
    ISHIKAWA,
    #[serde(rename = "jp_18")]
    FUKUI,
    #[serde(rename = "jp_19")]
    YAMANASHI,
    #[serde(rename = "jp_20")]
    NAGANO,
    #[serde(rename = "jp_21")]
    GIFU,
    #[serde(rename = "jp_22")]
    SHIZUOKA,
    #[serde(rename = "jp_23")]
    AICHI,
    #[serde(rename = "jp_24")]
    MIE,
    #[serde(rename = "jp_25")]
    SHIGA,
    #[serde(rename = "jp_26")]
    KYOTO,
    #[serde(rename = "jp_27")]
    OSAKA,
    #[serde(rename = "jp_28")]
    HYOUGO,
    #[serde(rename = "jp_29")]
    NARA,
    #[serde(rename = "jp_30")]
    WAKAYAMA,
    #[serde(rename = "jp_31")]
    TOTTORI,
    #[serde(rename = "jp_32")]
    SHIMANE,
    #[serde(rename = "jp_33")]
    OKAYAMA,
    #[serde(rename = "jp_34")]
    HIROSHIMA,
    #[serde(rename = "jp_35")]
    YAMAGUCHI,
    #[serde(rename = "jp_36")]
    TOKUSHIMA,
    #[serde(rename = "jp_37")]
    KAGAWA,
    #[serde(rename = "jp_38")]
    EHIME,
    #[serde(rename = "jp_39")]
    KOUCHI,
    #[serde(rename = "jp_40")]
    FUKUOKA,
    #[serde(rename = "jp_41")]
    SAGA,
    #[serde(rename = "jp_42")]
    NAGASAKI,
    #[serde(rename = "jp_43")]
    KUMAMOTO,
    #[serde(rename = "jp_44")]
    OITA,
    #[serde(rename = "jp_45")]
    MIYAZAKI,
    #[serde(rename = "jp_46")]
    KAGOSHIMA,
    #[serde(rename = "jp_47")]
    OKINAWA,
    #[serde(rename = "tw_01")]
    TAIPEI_CITY,
    #[serde(rename = "tw_02")]
    NEW_TAIPEI_CITY,
    #[serde(rename = "tw_03")]
    TAOYUAN_CITY,
    #[serde(rename = "tw_04")]
    TAICHUNG_CITY,
    #[serde(rename = "tw_05")]
    TAINAN_CITY,
    #[serde(rename = "tw_06")]
    KAOHSIUNG_CITY,
    #[serde(rename = "tw_07")]
    KEELUNG_CITY,
    #[serde(rename = "tw_08")]
    HSINCHU_CITY,
    #[serde(rename = "tw_09")]
    CHIAYI_CITY,
    #[serde(rename = "tw_10")]
    HSINCHU_COUNTY,
    #[serde(rename = "tw_11")]
    MIAOLI_COUNTY,
    #[serde(rename = "tw_12")]
    CHANGHUA_COUNTY,
    #[serde(rename = "tw_13")]
    NANTOU_COUNTY,
    #[serde(rename = "tw_14")]
    YUNLIN_COUNTY,
    #[serde(rename = "tw_15")]
    CHIAYI_COUNTY,
    #[serde(rename = "tw_16")]
    PINGTUNG_COUNTY,
    #[serde(rename = "tw_17")]
    YILAN_COUNTY,
    #[serde(rename = "tw_18")]
    HUALIEN_COUNTY,
    #[serde(rename = "tw_19")]
    TAITUNG_COUNTY,
    #[serde(rename = "tw_20")]
    PENGHU_COUNTY,
    #[serde(rename = "tw_21")]
    KINMEN_COUNTY,
    #[serde(rename = "tw_22")]
    LIENCHIANG_COUNTY,
    #[serde(rename = "th_01")]
    BANGKOK,
    #[serde(rename = "th_02")]
    PATTAYA,
    #[serde(rename = "th_03")]
    NORTHERN,
    #[serde(rename = "th_04")]
    CENTRAL,
    #[serde(rename = "th_05")]
    SOUTHERN,
    #[serde(rename = "th_06")]
    EASTERN,
    #[serde(rename = "th_07")]
    NORTHEASTERN,
    #[serde(rename = "th_08")]
    WESTERN,
    #[serde(rename = "id_01")]
    BALI,
    #[serde(rename = "id_02")]
    BANDUNG,
    #[serde(rename = "id_03")]
    BANJARMASIN,
    #[serde(rename = "id_04")]
    JABODETABEK,
    #[serde(rename = "id_05")]
    MAKASSAR,
    #[serde(rename = "id_06")]
    MEDAN,
    #[serde(rename = "id_07")]
    PALEMBANG,
    #[serde(rename = "id_08")]
    SAMARINDA,
    #[serde(rename = "id_09")]
    SEMARANG,
    #[serde(rename = "id_10")]
    SURABAYA,
    #[serde(rename = "id_11")]
    YOGYAKARTA,
    #[serde(rename = "id_12")]
    LAINNYA,
}

impl ToString for AreaDemographic {
    fn to_string(&self) -> String {
        match self {
            Self::HOKKAIDO => String::from("jp_01"),
            Self::AOMORI => String::from("jp_02"),
            Self::IWATE => String::from("jp_03"),
            Self::MIYAGI => String::from("jp_04"),
            Self::AKITA => String::from("jp_05"),
            Self::YAMAGATA => String::from("jp_06"),
            Self::FUKUSHIMA => String::from("jp_07"),
            Self::IBARAKI => String::from("jp_08"),
            Self::TOCHIGI => String::from("jp_09"),
            Self::GUNMA => String::from("jp_10"),
            Self::SAITAMA => String::from("jp_11"),
            Self::CHIBA => String::from("jp_12"),
            Self::TOKYO => String::from("jp_13"),
            Self::KANAGAWA => String::from("jp_14"),
            Self::NIIGATA => String::from("jp_15"),
            Self::TOYAMA => String::from("jp_16"),
            Self::ISHIKAWA => String::from("jp_17"),
            Self::FUKUI => String::from("jp_18"),
            Self::YAMANASHI => String::from("jp_19"),
            Self::NAGANO => String::from("jp_20"),
            Self::GIFU => String::from("jp_21"),
            Self::SHIZUOKA => String::from("jp_22"),
            Self::AICHI => String::from("jp_23"),
            Self::MIE => String::from("jp_24"),
            Self::SHIGA => String::from("jp_25"),
            Self::KYOTO => String::from("jp_26"),
            Self::OSAKA => String::from("jp_27"),
            Self::HYOUGO => String::from("jp_28"),
            Self::NARA => String::from("jp_29"),
            Self::WAKAYAMA => String::from("jp_30"),
            Self::TOTTORI => String::from("jp_31"),
            Self::SHIMANE => String::from("jp_32"),
            Self::OKAYAMA => String::from("jp_33"),
            Self::HIROSHIMA => String::from("jp_34"),
            Self::YAMAGUCHI => String::from("jp_35"),
            Self::TOKUSHIMA => String::from("jp_36"),
            Self::KAGAWA => String::from("jp_37"),
            Self::EHIME => String::from("jp_38"),
            Self::KOUCHI => String::from("jp_39"),
            Self::FUKUOKA => String::from("jp_40"),
            Self::SAGA => String::from("jp_41"),
            Self::NAGASAKI => String::from("jp_42"),
            Self::KUMAMOTO => String::from("jp_43"),
            Self::OITA => String::from("jp_44"),
            Self::MIYAZAKI => String::from("jp_45"),
            Self::KAGOSHIMA => String::from("jp_46"),
            Self::OKINAWA => String::from("jp_47"),
            Self::TAIPEI_CITY => String::from("tw_01"),
            Self::NEW_TAIPEI_CITY => String::from("tw_02"),
            Self::TAOYUAN_CITY => String::from("tw_03"),
            Self::TAICHUNG_CITY => String::from("tw_04"),
            Self::TAINAN_CITY => String::from("tw_05"),
            Self::KAOHSIUNG_CITY => String::from("tw_06"),
            Self::KEELUNG_CITY => String::from("tw_07"),
            Self::HSINCHU_CITY => String::from("tw_08"),
            Self::CHIAYI_CITY => String::from("tw_09"),
            Self::HSINCHU_COUNTY => String::from("tw_10"),
            Self::MIAOLI_COUNTY => String::from("tw_11"),
            Self::CHANGHUA_COUNTY => String::from("tw_12"),
            Self::NANTOU_COUNTY => String::from("tw_13"),
            Self::YUNLIN_COUNTY => String::from("tw_14"),
            Self::CHIAYI_COUNTY => String::from("tw_15"),
            Self::PINGTUNG_COUNTY => String::from("tw_16"),
            Self::YILAN_COUNTY => String::from("tw_17"),
            Self::HUALIEN_COUNTY => String::from("tw_18"),
            Self::TAITUNG_COUNTY => String::from("tw_19"),
            Self::PENGHU_COUNTY => String::from("tw_20"),
            Self::KINMEN_COUNTY => String::from("tw_21"),
            Self::LIENCHIANG_COUNTY => String::from("tw_22"),
            Self::BANGKOK => String::from("th_01"),
            Self::PATTAYA => String::from("th_02"),
            Self::NORTHERN => String::from("th_03"),
            Self::CENTRAL => String::from("th_04"),
            Self::SOUTHERN => String::from("th_05"),
            Self::EASTERN => String::from("th_06"),
            Self::NORTHEASTERN => String::from("th_07"),
            Self::WESTERN => String::from("th_08"),
            Self::BALI => String::from("id_01"),
            Self::BANDUNG => String::from("id_02"),
            Self::BANJARMASIN => String::from("id_03"),
            Self::JABODETABEK => String::from("id_04"),
            Self::MAKASSAR => String::from("id_05"),
            Self::MEDAN => String::from("id_06"),
            Self::PALEMBANG => String::from("id_07"),
            Self::SAMARINDA => String::from("id_08"),
            Self::SEMARANG => String::from("id_09"),
            Self::SURABAYA => String::from("id_10"),
            Self::YOGYAKARTA => String::from("id_11"),
            Self::LAINNYA => String::from("id_12"),
        }
    }
}

impl Default for AreaDemographic {
    fn default() -> AreaDemographic {
        Self::HOKKAIDO
    }
}
