/*
* Copyright 2023 nanato12
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagemapVideo {
    #[serde(rename = "originalContentUrl", skip_serializing_if = "Option::is_none")]
    pub original_content_url: Option<String>,
    #[serde(rename = "previewImageUrl", skip_serializing_if = "Option::is_none")]
    pub preview_image_url: Option<String>,
    #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
    pub area: Option<Box<crate::models::ImagemapArea>>,
    #[serde(rename = "externalLink", skip_serializing_if = "Option::is_none")]
    pub external_link: Option<Box<crate::models::ImagemapExternalLink>>,
}

impl ImagemapVideo {
    pub fn new() -> ImagemapVideo {
        ImagemapVideo {
            original_content_url: None,
            preview_image_url: None,
            area: None,
            external_link: None,
        }
    }
}
