/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{CameraAction, CameraRollAction, ClipboardAction, DatetimePickerAction, LocationAction, MessageAction, PostbackAction, RichMenuSwitchAction, UriAction};

/// Action : Action
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Action {
    #[serde(rename="camera")]
    Camera(CameraAction),
    #[serde(rename="cameraRoll")]
    CameraRoll(CameraRollAction),
    #[serde(rename="clipboard")]
    Clipboard(ClipboardAction),
    #[serde(rename="datetimepicker")]
    DatetimePicker(DatetimePickerAction),
    #[serde(rename="location")]
    Location(LocationAction),
    #[serde(rename="message")]
    Message(MessageAction),
    #[serde(rename="postback")]
    Postback(PostbackAction),
    #[serde(rename="richmenuswitch")]
    RichMenuSwitch(RichMenuSwitchAction),
    #[serde(rename="uri")]
    Uri(UriAction),
}

impl Default for Action {
    fn default() -> Self {
        Self::Camera(CameraAction::default())
    }
}


