/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgeDemographicFilter {
    /// Type of demographic filter
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "gte", skip_serializing_if = "Option::is_none")]
    pub gte: Option<models::AgeDemographic>,
    #[serde(rename = "lt", skip_serializing_if = "Option::is_none")]
    pub lt: Option<models::AgeDemographic>,
}

impl AgeDemographicFilter {
    pub fn new() -> AgeDemographicFilter {
        AgeDemographicFilter {
            r#type: Some("age".to_string()),
            gte: None,
            lt: None,
        }
    }
}

