/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioMessage {
    /// Type of message
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
    pub quick_reply: Option<Box<models::QuickReply>>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<Box<models::Sender>>,
    #[serde(rename = "originalContentUrl")]
    pub original_content_url: String,
    #[serde(rename = "duration")]
    pub duration: i64,
}

impl AudioMessage {
    pub fn new(original_content_url: String, duration: i64) -> AudioMessage {
        AudioMessage {
            r#type:Some("audio".to_owned()),
            quick_reply: None,
            sender: None,
            original_content_url,
            duration,
        }
    }
}

