/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CarouselTemplate {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "columns")]
    pub columns: Vec<models::CarouselColumn>,
    #[serde(rename = "imageAspectRatio", skip_serializing_if = "Option::is_none")]
    pub image_aspect_ratio: Option<String>,
    #[serde(rename = "imageSize", skip_serializing_if = "Option::is_none")]
    pub image_size: Option<String>,
}

impl CarouselTemplate {
    pub fn new(columns: Vec<models::CarouselColumn>) -> CarouselTemplate {
        CarouselTemplate {
            r#type:Some("carousel".to_owned()),
            columns,
            image_aspect_ratio: None,
            image_size: None,
        }
    }
}

