/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatReference : Chat reference
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatReference {
    /// The target user ID
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl ChatReference {
    /// Chat reference
    pub fn new(user_id: String) -> ChatReference {
        ChatReference {
            user_id,
        }
    }
}

