/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DemographicFilter : Demographic filter
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum DemographicFilter {
    #[serde(rename = "age")]
    AgeDemographicFilter(models::AgeDemographicFilter),
    #[serde(rename = "appType")]
    AppTypeDemographicFilter(models::AppTypeDemographicFilter),
    #[serde(rename = "area")]
    AreaDemographicFilter(models::AreaDemographicFilter),
    #[serde(rename = "gender")]
    GenderDemographicFilter(models::GenderDemographicFilter),
    #[serde(rename = "operator")]
    OperatorDemographicFilter(models::OperatorDemographicFilter),
    #[serde(rename = "subscriptionPeriod")]
    SubscriptionPeriodDemographicFilter(models::SubscriptionPeriodDemographicFilter),
    #[serde(other)]
    UnknownDemographicFilter,
}

impl Default for DemographicFilter {
    fn default() -> DemographicFilter {
        DemographicFilter::AgeDemographicFilter(Default::default())
    }
}
