/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountFixedPriceInfoResponse {
/// Currency code (e.g., JPY, THB, TWD).
#[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Currency>,
#[serde(rename = "fixedAmount", skip_serializing_if = "Option::is_none")]
    pub fixed_amount: Option<i64>,
}

impl DiscountFixedPriceInfoResponse {
pub fn new() -> DiscountFixedPriceInfoResponse {
        DiscountFixedPriceInfoResponse {
currency: None,
fixed_amount: None,
}
    }
}
/// Currency code (e.g., JPY, THB, TWD).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum Currency {
#[serde(rename = "JPY")]
    Jpy,
#[serde(rename = "THB")]
    Thb,
#[serde(rename = "TWD")]
    Twd,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Jpy
    }
}
