/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{FlexBubble, FlexCarousel};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FlexContainer {
    #[serde(rename="bubble")]
    Bubble(FlexBubble),
    #[serde(rename="carousel")]
    Carousel(FlexCarousel),
}

impl Default for FlexContainer {
    fn default() -> Self {
        Self::Bubble(FlexBubble::default())
    }
}


