/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlexCarousel {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "contents")]
    pub contents: Vec<models::FlexBubble>,
}

impl FlexCarousel {
    pub fn new(contents: Vec<models::FlexBubble>) -> FlexCarousel {
        FlexCarousel {
            r#type:Some("carousel".to_string()),
            contents,
        }
    }
}

