/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlexOffset : You can specify the offset of a component with the `offset*` property, in pixels or with a keyword. You can also specify the percentage to the box width for `offsetStart` and `offsetEnd` and to the box height for `offsetTop` and `offsetBottom`. FlexOffset just provides only keywords. 
/// You can specify the offset of a component with the `offset*` property, in pixels or with a keyword. You can also specify the percentage to the box width for `offsetStart` and `offsetEnd` and to the box height for `offsetTop` and `offsetBottom`. FlexOffset just provides only keywords. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum FlexOffset {
#[serde(rename = "none")]
    None,
#[serde(rename = "xs")]
    Xs,
#[serde(rename = "sm")]
    Sm,
#[serde(rename = "md")]
    Md,
#[serde(rename = "lg")]
    Lg,
#[serde(rename = "xl")]
    Xl,
#[serde(rename = "xxl")]
    Xxl,
}

impl std::fmt::Display for FlexOffset {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
Self::None => write!(f, "none"),
Self::Xs => write!(f, "xs"),
Self::Sm => write!(f, "sm"),
Self::Md => write!(f, "md"),
Self::Lg => write!(f, "lg"),
Self::Xl => write!(f, "xl"),
Self::Xxl => write!(f, "xxl"),
}
    }
}

impl Default for FlexOffset {
    fn default() -> FlexOffset {
        Self::None
    }
}
