/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetMembershipSubscriptionResponse : A user's membership subscription status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMembershipSubscriptionResponse {
    /// List of subscription information
    #[serde(rename = "subscriptions")]
    pub subscriptions: Vec<models::Subscription>,
}

impl GetMembershipSubscriptionResponse {
    /// A user's membership subscription status
    pub fn new(subscriptions: Vec<models::Subscription>) -> GetMembershipSubscriptionResponse {
        GetMembershipSubscriptionResponse {
            subscriptions,
        }
    }
}

