/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetJoinedMembershipUsersResponse : List of users who have joined the membership

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJoinedMembershipUsersResponse {
    /// A list of user IDs who joined the membership. Users who have not agreed to the bot user agreement, are not following the bot, or are not active will be excluded. If there are no users in the membership, an empty list will be returned.
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
    /// A continuation token to get next remaining membership user IDs. Returned only when there are remaining user IDs that weren't returned in the userIds property in the previous request. The continuation token expires in 24 hours (86,400 seconds).  
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl GetJoinedMembershipUsersResponse {
    /// List of users who have joined the membership
    pub fn new(user_ids: Vec<String>) -> GetJoinedMembershipUsersResponse {
        GetJoinedMembershipUsersResponse {
            user_ids,
            next: None,
        }
    }
}
