/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetJoinedMembershipUsersResponse : List of users who have joined the membership
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetJoinedMembershipUsersResponse {
    /// A list of user IDs who joined the membership. Users who have not agreed to the bot user agreement, are not following the bot, or are not active will be excluded. If there are no users in the membership, an empty list will be returned. 
    #[serde(rename = "userIds")]
    pub user_ids: Vec<String>,
    /// A continuation token to get next remaining membership user IDs. Returned only when there are remaining user IDs that weren't returned in the userIds property in the previous request. The continuation token expires in 24 hours (86,400 seconds).  
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl GetJoinedMembershipUsersResponse {
    /// List of users who have joined the membership
    pub fn new(user_ids: Vec<String>) -> GetJoinedMembershipUsersResponse {
        GetJoinedMembershipUsersResponse {
            user_ids,
            next: None,
        }
    }
}

