/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAggregationUnitUsageResponse {
    /// Number of aggregation units used this month.
    #[serde(rename = "numOfCustomAggregationUnits")]
    pub num_of_custom_aggregation_units: i64,
}

impl GetAggregationUnitUsageResponse {
    pub fn new(num_of_custom_aggregation_units: i64) -> GetAggregationUnitUsageResponse {
        GetAggregationUnitUsageResponse {
            num_of_custom_aggregation_units,
        }
    }
}

