/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupSummaryResponse {
    /// Group ID
    #[serde(rename = "groupId")]
    pub group_id: String,
    /// Group name
    #[serde(rename = "groupName")]
    pub group_name: String,
    /// Group icon URL. Not included in the response if the user doesn't set a group profile icon.
    #[serde(rename = "pictureUrl", skip_serializing_if = "Option::is_none")]
    pub picture_url: Option<String>,
}

impl GroupSummaryResponse {
    pub fn new(group_id: String, group_name: String) -> GroupSummaryResponse {
        GroupSummaryResponse {
            group_id,
            group_name,
            picture_url: None,
        }
    }
}

