/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagemapBaseSize {
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "width")]
    pub width: i32,
}

impl ImagemapBaseSize {
    pub fn new(height: i32, width: i32) -> ImagemapBaseSize {
        ImagemapBaseSize {
            height,
            width,
        }
    }
}

