/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagemapExternalLink {
    #[serde(rename = "linkUri", skip_serializing_if = "Option::is_none")]
    pub link_uri: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl ImagemapExternalLink {
    pub fn new() -> ImagemapExternalLink {
        ImagemapExternalLink {
            link_uri: None,
            label: None,
        }
    }
}

