/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Limit : Limit of the Narrowcast
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Limit {
    /// The maximum number of narrowcast messages to send. Use this parameter to limit the number of narrowcast messages sent. The recipients will be chosen at random. 
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<i32>,
    /// If true, the message will be sent within the maximum number of deliverable messages. The default value is `false`.  Targets will be selected at random. 
    #[serde(rename = "upToRemainingQuota", skip_serializing_if = "Option::is_none")]
    pub up_to_remaining_quota: Option<bool>,
}

impl Limit {
    /// Limit of the Narrowcast
    pub fn new() -> Limit {
        Limit {
            max: None,
            up_to_remaining_quota: None,
        }
    }
}

