/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembersIdsResponse {
    /// List of user IDs of members in the group chat. Only users of LINE for iOS and LINE for Android are included in `memberIds`.
    #[serde(rename = "memberIds")]
    pub member_ids: Vec<String>,
    /// A continuation token to get the next array of user IDs of the members in the group chat. Returned only when there are remaining user IDs that were not returned in `memberIds` in the original request. 
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl MembersIdsResponse {
    pub fn new(member_ids: Vec<String>) -> MembersIdsResponse {
        MembersIdsResponse {
            member_ids,
            next: None,
        }
    }
}

