/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{AllMentionTarget, UserMentionTarget};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MentionTarget {
    #[serde(rename="all")]
    AllMentionTarget(AllMentionTarget),
    #[serde(rename="user")]
    UserMentionTarget(UserMentionTarget),
}

impl Default for MentionTarget {
    fn default() -> Self {
        Self::AllMentionTarget(AllMentionTarget::default())
    }
}


