/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MentionSubstitutionObject : An object representing a mention substitution.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MentionSubstitutionObject {
    /// Type of substitution object
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "mentionee")]
    pub mentionee: Box<models::MentionTarget>,
}

impl MentionSubstitutionObject {
    /// An object representing a mention substitution.
    pub fn new(mentionee: models::MentionTarget) -> MentionSubstitutionObject {
        MentionSubstitutionObject {
            r#type:Some("mention".to_owned()),
            mentionee: Box::new(mentionee),
        }
    }
}

