/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use super::{AudioMessage, FlexMessage, ImageMessage, ImagemapMessage, LocationMessage, StickerMessage, TemplateMessage, TextMessage, TextMessageV2, VideoMessage};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Message {
    #[serde(rename="audio")]
    Audio(AudioMessage),
    #[serde(rename="flex")]
    Flex(FlexMessage),
    #[serde(rename="image")]
    Image(ImageMessage),
    #[serde(rename="imagemap")]
    Imagemap(ImagemapMessage),
    #[serde(rename="location")]
    Location(LocationMessage),
    #[serde(rename="sticker")]
    Sticker(StickerMessage),
    #[serde(rename="template")]
    Template(TemplateMessage),
    #[serde(rename="text")]
    Text(TextMessage),
    #[serde(rename="textV2")]
    TextV2(TextMessageV2),
    #[serde(rename="video")]
    Video(VideoMessage),
}

impl Default for Message {
    fn default() -> Self {
        Self::Audio(AudioMessage::default())
    }
}


