/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessagingApiPagerCouponListResponse : Paginated response object containing a list of coupons.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingApiPagerCouponListResponse {
    /// List of coupon summary objects.
    #[serde(rename = "items")]
    pub items: Vec<models::CouponListResponse>,
    /// Token for fetching the next page of results.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl MessagingApiPagerCouponListResponse {
    /// Paginated response object containing a list of coupons.
    pub fn new(items: Vec<models::CouponListResponse>) -> MessagingApiPagerCouponListResponse {
        MessagingApiPagerCouponListResponse { items, next: None }
    }
}
