/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NarrowcastRequest {
    /// List of Message objects.
    #[serde(rename = "messages")]
    pub messages: Vec<models::Message>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<Box<models::Recipient>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::Filter>>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Box<models::Limit>>,
    /// `true`: The user doesn’t receive a push notification when a message is sent. `false`: The user receives a push notification when the message is sent (unless they have disabled push notifications in LINE and/or their device). The default value is false. 
    #[serde(rename = "notificationDisabled", skip_serializing_if = "Option::is_none")]
    pub notification_disabled: Option<bool>,
}

impl NarrowcastRequest {
    pub fn new(messages: Vec<models::Message>) -> NarrowcastRequest {
        NarrowcastRequest {
            messages,
            recipient: None,
            filter: None,
            limit: None,
            notification_disabled: None,
        }
    }
}

