/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperatorDemographicFilter {
    /// Type of demographic filter
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "and", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<models::DemographicFilter>>,
    #[serde(rename = "or", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<models::DemographicFilter>>,
    #[serde(rename = "not", skip_serializing_if = "Option::is_none")]
    pub not: Option<Box<models::DemographicFilter>>,
}

impl OperatorDemographicFilter {
    pub fn new() -> OperatorDemographicFilter {
        OperatorDemographicFilter {
            r#type: Some("operator".to_string()),
            and: None,
            or: None,
            not: None,
        }
    }
}

