/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperatorRecipient {
    /// Type of recipient
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Create a new recipient object by taking the logical conjunction (AND) of the specified array of recipient objects. 
    #[serde(rename = "and", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<models::Recipient>>,
    /// Create a new recipient object by taking the logical disjunction (OR) of the specified array of recipient objects. 
    #[serde(rename = "or", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<models::Recipient>>,
    #[serde(rename = "not", skip_serializing_if = "Option::is_none")]
    pub not: Option<Box<models::Recipient>>,
}

impl OperatorRecipient {
    pub fn new() -> OperatorRecipient {
        OperatorRecipient {
            r#type: Some("operator".to_owned()),
            and: None,
            or: None,
            not: None,
        }
    }
}

