/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PnpMessagesRequest {
    /// Message to be sent.
    #[serde(rename = "messages")]
    pub messages: Vec<models::Message>,
    /// Message destination. Specify a phone number that has been normalized to E.164 format and hashed with SHA256.
    #[serde(rename = "to")]
    pub to: String,
    /// `true`: The user doesn’t receive a push notification when a message is sent. `false`: The user receives a push notification when the message is sent (unless they have disabled push notifications in LINE and/or their device). The default value is false. 
    #[serde(rename = "notificationDisabled", skip_serializing_if = "Option::is_none")]
    pub notification_disabled: Option<bool>,
}

impl PnpMessagesRequest {
    pub fn new(messages: Vec<models::Message>, to: String) -> PnpMessagesRequest {
        PnpMessagesRequest {
            messages,
            to,
            notification_disabled: None,
        }
    }
}

