/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuickReply : Quick reply
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuickReply {
    /// Quick reply button objects.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::QuickReplyItem>>,
}

impl QuickReply {
    /// Quick reply
    pub fn new() -> QuickReply {
        QuickReply {
            items: None,
        }
    }
}

