/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaType : One of the following values to indicate whether a target limit is set or not.
/// One of the following values to indicate whether a target limit is set or not.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuotaType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "limited")]
    Limited,

}

impl std::fmt::Display for QuotaType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Limited => write!(f, "limited"),
        }
    }
}

impl Default for QuotaType {
    fn default() -> QuotaType {
        Self::None
    }
}

