/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaConsumptionResponse {
    /// The number of sent messages in the current month
    #[serde(rename = "totalUsage")]
    pub total_usage: i64,
}

impl QuotaConsumptionResponse {
    pub fn new(total_usage: i64) -> QuotaConsumptionResponse {
        QuotaConsumptionResponse {
            total_usage,
        }
    }
}

