/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RichMenuSize : Rich menu size
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RichMenuSize {
    /// width
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    /// height
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
}

impl RichMenuSize {
    /// Rich menu size
    pub fn new() -> RichMenuSize {
        RichMenuSize {
            width: None,
            height: None,
        }
    }
}

