/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RichMenuSwitchAction {
    /// Type of action
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Label for the action.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(rename = "richMenuAliasId", skip_serializing_if = "Option::is_none")]
    pub rich_menu_alias_id: Option<String>,
}

impl RichMenuSwitchAction {
    pub fn new() -> RichMenuSwitchAction {
        RichMenuSwitchAction {
            r#type: Some("richmenuswitch".to_string()),
            label: None,
            data: None,
            rich_menu_alias_id: None,
        }
    }
}

