/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoomMemberCountResponse {
    /// The count of members in the multi-person chat. The number returned excludes the LINE Official Account.
    #[serde(rename = "count")]
    pub count: i32,
}

impl RoomMemberCountResponse {
    pub fn new(count: i32) -> RoomMemberCountResponse {
        RoomMemberCountResponse {
            count,
        }
    }
}

