/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShowLoadingAnimationRequest {
    /// User ID of the target user for whom the loading animation is to be displayed.
    #[serde(rename = "chatId")]
    pub chat_id: String,
    /// The number of seconds to display the loading indicator. It must be a multiple of 5. The maximum value is 60 seconds.
    #[serde(rename = "loadingSeconds", skip_serializing_if = "Option::is_none")]
    pub loading_seconds: Option<i32>,
}

impl ShowLoadingAnimationRequest {
    pub fn new(chat_id: String) -> ShowLoadingAnimationRequest {
        ShowLoadingAnimationRequest {
            chat_id,
            loading_seconds: None,
        }
    }
}
