/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShowLoadingAnimationRequest {
    /// User ID of the target user for whom the loading animation is to be displayed.
    #[serde(rename = "chatId")]
    pub chat_id: String,
    /// The number of seconds to display the loading indicator. It must be a multiple of 5. The maximum value is 60 seconds. 
    #[serde(rename = "loadingSeconds", skip_serializing_if = "Option::is_none")]
    pub loading_seconds: Option<i32>,
}

impl ShowLoadingAnimationRequest {
    pub fn new(chat_id: String) -> ShowLoadingAnimationRequest {
        ShowLoadingAnimationRequest {
            chat_id,
            loading_seconds: None,
        }
    }
}

