/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscribedMembershipPlan : Object containing information about the membership plan.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscribedMembershipPlan {
    /// Membership plan ID.
    #[serde(rename = "membershipId")]
    pub membership_id: i32,
    /// Membership plan name.
    #[serde(rename = "title")]
    pub title: String,
    /// Membership plan description.
    #[serde(rename = "description")]
    pub description: String,
    /// List of membership plan perks.
    #[serde(rename = "benefits")]
    pub benefits: Vec<String>,
    /// Monthly fee for membership plan. (e.g. 1500.00)
    #[serde(rename = "price")]
    pub price: f64,
    /// The currency of membership.price.
    #[serde(rename = "currency")]
    pub currency: Currency,
}

impl SubscribedMembershipPlan {
    /// Object containing information about the membership plan.
    pub fn new(membership_id: i32, title: String, description: String, benefits: Vec<String>, price: f64, currency: Currency) -> SubscribedMembershipPlan {
        SubscribedMembershipPlan {
            membership_id,
            title,
            description,
            benefits,
            price,
            currency,
        }
    }
}
/// The currency of membership.price.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "JPY")]
    Jpy,
    #[serde(rename = "TWD")]
    Twd,
    #[serde(rename = "THB")]
    Thb,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Jpy
    }
}

