/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRichMenuAliasRequest {
    /// The rich menu ID to be associated with the rich menu alias.
    #[serde(rename = "richMenuId")]
    pub rich_menu_id: String,
}

impl UpdateRichMenuAliasRequest {
    pub fn new(rich_menu_id: String) -> UpdateRichMenuAliasRequest {
        UpdateRichMenuAliasRequest {
            rich_menu_id,
        }
    }
}

