/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UriImagemapAction {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "area")]
    pub area: Box<models::ImagemapArea>,
    #[serde(rename = "linkUri")]
    pub link_uri: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl UriImagemapAction {
    pub fn new(area: models::ImagemapArea, link_uri: String) -> UriImagemapAction {
        UriImagemapAction {
            r#type: Some("uri".to_string()),
            area: Box::new(area),
            link_uri,
            label: None,
        }
    }
}
