/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateMessageRequest {
    /// Array of message objects to validate
    #[serde(rename = "messages")]
    pub messages: Vec<models::Message>,
}

impl ValidateMessageRequest {
    pub fn new(messages: Vec<models::Message>) -> ValidateMessageRequest {
        ValidateMessageRequest {
            messages,
        }
    }
}

