[package]
name = "line_webhook"
version = "1.0.2"
authors = ["OpenAPI Generator team and contributors"]
description = "Webhook event definition of the LINE Messaging API"
# Override this license by providing a License Object in the OpenAPI.
license = "Unlicense"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_repr.workspace = true
url.workspace = true
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["client", "client-legacy", "http1", "http2"] }
http-body-util.workspace = true
base64.workspace = true
futures.workspace = true
