changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - feature
    - title: 📄 New Documentation
      labels:
        - documentation
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🔧 Refactoring
      labels:
        - refactor
    - title: ✅ Changes to GitHub Actions
      labels:
        - actions
    - title: 🎉 Changes for Release
      labels:
        - release
    - title: Other Changes
      labels:
        - "*"
