/*
* Copyright 2023 nanato12
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiffFeatures {
    /// `true` if the LIFF app supports Bluetooth® Low Energy for LINE Things. `false` otherwise.
    #[serde(rename = "ble", skip_serializing_if = "Option::is_none")]
    pub ble: Option<bool>,
    /// `true` to use the 2D code reader in the LIFF app. false otherwise. The default value is `false`.
    #[serde(rename = "qrCode", skip_serializing_if = "Option::is_none")]
    pub qr_code: Option<bool>,
}

impl LiffFeatures {
    pub fn new() -> LiffFeatures {
        LiffFeatures {
            ble: None,
            qr_code: None,
        }
    }
}
