/*
* Copyright 2023 nanato12
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CarouselColumn : Column object for carousel template.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CarouselColumn {
    #[serde(rename = "thumbnailImageUrl", skip_serializing_if = "Option::is_none")]
    pub thumbnail_image_url: Option<String>,
    #[serde(rename = "imageBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub image_background_color: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "defaultAction", skip_serializing_if = "Option::is_none")]
    pub default_action: Option<Box<crate::messaging_api::models::Action>>,
    #[serde(rename = "actions")]
    pub actions: Vec<crate::messaging_api::models::Action>,
}

impl CarouselColumn {
    /// Column object for carousel template.
    pub fn new(text: String, actions: Vec<crate::messaging_api::models::Action>) -> CarouselColumn {
        CarouselColumn {
            thumbnail_image_url: None,
            image_background_color: None,
            title: None,
            text,
            default_action: None,
            actions,
        }
    }
}


