/*
* Copyright 2023 nanato12
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlexBoxLinearGradient {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "angle", skip_serializing_if = "Option::is_none")]
    pub angle: Option<String>,
    #[serde(rename = "startColor", skip_serializing_if = "Option::is_none")]
    pub start_color: Option<String>,
    #[serde(rename = "endColor", skip_serializing_if = "Option::is_none")]
    pub end_color: Option<String>,
    #[serde(rename = "centerColor", skip_serializing_if = "Option::is_none")]
    pub center_color: Option<String>,
    #[serde(rename = "centerPosition", skip_serializing_if = "Option::is_none")]
    pub center_position: Option<String>,
}

impl FlexBoxLinearGradient {
    pub fn new(r#type: String) -> FlexBoxLinearGradient {
        FlexBoxLinearGradient {
            r#type,
            angle: None,
            start_color: None,
            end_color: None,
            center_color: None,
            center_position: None,
        }
    }
}


