/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * Membership API
 *
 * This document describes LINE Official Account Membership API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// MembershipUser : Object containing user membership subscription information.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipUser {
    /// The user's member number in the membership plan.
    #[serde(rename = "membershipNo")]
    pub membership_no: i32,
    /// UNIX timestamp at which the user subscribed to the membership.
    #[serde(rename = "joinedTime")]
    pub joined_time: i32,
    /// Next payment date for membership plan. - Format: yyyy-MM-dd (e.g. 2024-02-08) - Timezone: UTC+9
    #[serde(rename = "nextBillingDate")]
    pub next_billing_date: String,
    /// The period of time in months that the user has been subscribed to a membership plan. If a user previously canceled and then re-subscribed to the same membership plan, only the period after the re-subscription will be counted.
    #[serde(rename = "totalSubscriptionMonths")]
    pub total_subscription_months: i32,
}

impl MembershipUser {
    /// Object containing user membership subscription information.
    pub fn new(
        membership_no: i32,
        joined_time: i32,
        next_billing_date: String,
        total_subscription_months: i32,
    ) -> MembershipUser {
        MembershipUser {
            membership_no,
            joined_time,
            next_billing_date,
            total_subscription_months,
        }
    }
}
