/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * Membership API
 *
 * This document describes LINE Official Account Membership API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Subscription : An array of memberships.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscription {
    #[serde(rename = "membership")]
    pub membership: Box<crate::models::MembershipMeta>,
    #[serde(rename = "user")]
    pub user: Box<crate::models::MembershipUser>,
}

impl Subscription {
    /// An array of memberships.
    pub fn new(
        membership: crate::models::MembershipMeta,
        user: crate::models::MembershipUser,
    ) -> Subscription {
        Subscription {
            membership: Box::new(membership),
            user: Box::new(user),
        }
    }
}
