/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::line_messaging_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PnpTemplatedMessageRequest {
    /// Message destination. Specify a phone number that has been normalized to E.164 format and hashed with SHA256.
    #[serde(rename = "to")]
    pub to: String,
    /// Specify the key of the template you want to send. For available keys, see https://developers.line.biz/en/docs/partner-docs/line-notification-messages/template/#templates
    #[serde(rename = "templateKey")]
    pub template_key: String,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::PnpTemplatedMessageBody>>,
    /// Name of aggregation unit. Case-sensitive. For more information about assigning a unit name, see https://developers.line.biz/en/docs/messaging-api/unit-based-statistics-aggregation/#assign-names-to-units-when-sending-messages
    #[serde(
        rename = "customAggregationUnits",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_aggregation_units: Option<Vec<String>>,
}

impl PnpTemplatedMessageRequest {
    pub fn new(to: String, template_key: String) -> PnpTemplatedMessageRequest {
        PnpTemplatedMessageRequest {
            to,
            template_key,
            body: None,
            custom_aggregation_units: None,
        }
    }
}
