/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Emoji {
    /// Index position for a character in text, with the first character being at position 0.
    #[serde(rename = "index")]
    pub index: i32,
    /// The length of the LINE emoji string. For LINE emoji (hello), 7 is the length.
    #[serde(rename = "length")]
    pub length: i32,
    /// Product ID for a LINE emoji set.
    #[serde(rename = "productId")]
    pub product_id: String,
    /// ID for a LINE emoji inside a set.
    #[serde(rename = "emojiId")]
    pub emoji_id: String,
}

impl Emoji {
    pub fn new(index: i32, length: i32, product_id: String, emoji_id: String) -> Emoji {
        Emoji {
            index,
            length,
            product_id,
            emoji_id,
        }
    }
}
