/*
* Copyright (C) 2016 LINE Corp.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Event : Webhook event
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum Event {
    #[serde(rename = "message")]
    MessageEvent(models::MessageEvent),
    #[serde(rename = "unsend")]
    UnsendEvent(models::UnsendEvent),
    #[serde(rename = "follow")]
    FollowEvent(models::FollowEvent),
    #[serde(rename = "unfollow")]
    UnfollowEvent(models::UnfollowEvent),
    #[serde(rename = "join")]
    JoinEvent(models::JoinEvent),
    #[serde(rename = "leave")]
    LeaveEvent(models::LeaveEvent),
    #[serde(rename = "memberJoined")]
    MemberJoinedEvent(models::MemberJoinedEvent),
    #[serde(rename = "memberLeft")]
    MemberLeftEvent(models::MemberLeftEvent),
    #[serde(rename = "postback")]
    PostbackEvent(models::PostbackEvent),
    #[serde(rename = "videoPlayComplete")]
    VideoPlayCompleteEvent(models::VideoPlayCompleteEvent),
    #[serde(rename = "beacon")]
    BeaconEvent(models::BeaconEvent),
    #[serde(rename = "accountLink")]
    AccountLinkEvent(models::AccountLinkEvent),
    #[serde(rename = "membership")]
    MembershipEvent(models::MembershipEvent),
    #[serde(rename = "module")]
    ModuleEvent(models::ModuleEvent),
    #[serde(rename = "activated")]
    ActivatedEvent(models::ActivatedEvent),
    #[serde(rename = "deactivated")]
    DeactivatedEvent(models::DeactivatedEvent),
    #[serde(rename = "botSuspended")]
    BotSuspendedEvent(models::BotSuspendedEvent),
    #[serde(rename = "botResumed")]
    BotResumedEvent(models::BotResumedEvent),
    #[serde(rename = "delivery")]
    PnpDeliveryCompletionEvent(models::PnpDeliveryCompletionEvent),
    #[serde(other)]
    Unknown,
}

impl Default for Event {
    fn default() -> Event {
        Event::MessageEvent(Default::default())
    }
}
