name: Rust

on:
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - "**.toml"
      - "**.rs"

  push:
    branches:
      - develop
    paths:
      - .github/workflows/rust.yml
      - "**.toml"
      - "**.rs"

jobs:
  build:
    name: Rust ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --tests

      - name: Build for examples
        run: cargo build --verbose
        working-directory: examples

      - name: Run tests for examples
        run: cargo test --verbose --tests
        working-directory: examples
