name: Rust

on:
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - "**.toml"
      - "**.rs"

  push:
    branches:
      - develop
    paths:
      - .github/workflows/rust.yml
      - "**.toml"
      - "**.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check formatting for examples
        run: cargo fmt --all -- --check
        working-directory: examples

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Clippy with rocket_support
        run: cargo clippy --all-targets --features rocket_support -- -D warnings

      - name: Clippy with actix_support
        run: cargo clippy --all-targets --features actix_support -- -D warnings

      - name: Clippy for examples
        run: cargo clippy --all-targets -- -D warnings
        working-directory: examples

  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build with rocket_support
        run: cargo build --verbose --features rocket_support

      - name: Build with actix_support
        run: cargo build --verbose --features actix_support

      - name: Build for examples
        run: cargo build --verbose
        working-directory: examples

      - name: Run tests for examples
        run: cargo test --verbose
        working-directory: examples

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run audit
        run: cargo audit --ignore RUSTSEC-2019-0020 --ignore RUSTSEC-2020-0151
