name: Rust

on:
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - "**.toml"
      - "**.rs"

  push:
    branches:
      - develop
    paths:
      - .github/workflows/rust.yml
      - "**.toml"
      - "**.rs"

jobs:
  build:
    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --tests
        continue-on-error: ${{ matrix.rust == 'nightly' }}

      - name: Build for examples
        run: cargo build --verbose
        working-directory: examples

      - name: Run tests for examples
        run: cargo test --verbose --tests
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        working-directory: examples
